[package]
name = "antbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.3", features = ["derive"] }
itertools = "=0.9.0"
itertools-num = "=0.1.3"
petgraph = "=0.5.0"