[package]
name = "antbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.3", features = ["derive"] }
itertools = "=0.9.0"

[[bin]]
name = "main"
# path = "src/1_1.rs"
# path = "src/1_6_triangle.rs"
# path = "src/1_6_ant.rs"
path = "src/binary_search.rs"
